{{- if .Values.ingress.mutual }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.name }}-mutual-tls
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
data:
  ca-bundle.pem: |-
    {{ ( printf "%s%s" "tls/" .Values.tls.mutual.cert | $.Files.Get) | b64enc }}
type: kubernetes.io/tls
{{- end }}
