apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.name }}-wildcard-tls
  namespace: openshift-ingress
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
data:
  tls.crt: |-
    {{ ( printf "%s%s" "tls/" .Values.tls.wildcard.cert | $.Files.Get) | b64enc }}
  tls.key: |-
    {{ ( printf "%s%s" "tls/" .Values.tls.wildcard.key | $.Files.Get) | b64enc }}
type: kubernetes.io/tls
