---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{.Values.ipFailover.instanceName}}-privileged-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
  - kind: ServiceAccount
    name: {{.Values.ipFailover.serviceAccountName}}
    namespace: {{.Values.ipFailover.namespace}}
